- birch-artifact-list-item.html
- bower.json
- Add debouncer
- Point clamp to my fork
> Add debouncer to resize listener

- birch-artifact-list-item-preview.html
> Changing to indexOf

- locales/birch-artifact-list-item_en.json
- Translation for contributed by
> Translation string for contributed by

- birch-artifact-list-item-preview.html
> Use http status codes

- birch-artifact-list-item.css
- birch-artifact-list-item.html
- test/tests.html
- Wrapped the title sections in template tags based on the showContributed flag
- Added ability to display the contributor
@liechtym / @jpodwys  / @jasonallen68
> Add feature to display contributor

- birch-artifact-list-item.css
- birch-artifact-list-item.html
- locales/birch-artifact-list-item_en.json
A corresponding PR also exists for the `birch-artifact-grid-item` component
- Add flag showMessages for toggling the exp
- In order for the flag to work a PR also needs to be merged to the `birch-artifact-viewer`
- Added sections for screening, processing, processing failed, and restricted
- Updated a translation string to include a period
@jasonallen68  / @jpodwys  / @liechtym
> Show messages

- birch-artifact-list-item.html
- Fix a bug where tags/counts were being displayed
- Prevent state check if experiment is turned off
> Prevent state check if Ex off, fix comments/tag display bug

- birch-artifact-list-item.html
- bower.json
- Used || when I needed &&
- Add processing exception for audio
> Exception for audio and fix checks

- birch-artifact-list-item.html
- Unnecessary outer div hiding
- Unnecessary javascript hiding
> Remove javascript unnecessary hiding

- birch-artifact-list-item.html
- Add tap listener to open contact card
> Fire event when the contributor is tapped

- locales/birch-artifact-list-item-preview_en.json
Adding translations for updated upload error messages
> Translations

- birch-artifact-list-item-preview.html
- Remove the old case statement
- If the status is another 400 error we are not checking for then use the try again or change format message
- Rename the mp3 prop to tryAgain
> Upload errors

- birch-artifact-list-item.css
- birch-artifact-list-item.html
- Update styles.
- Tweak some things.
> Fixing issues when contributor is shown (wasn't working before with contributors)

- birch-artifact-list-item.css
- birch-artifact-list-item.html
- test/tests.html
- Fix iPhone zooming in when pressing input.
- Adding e.preventDefault() so Firefox doesn't propagate the enter event.
- Adding a way to force an error so Jeff can test the error handling.
> Fixing styles, fixing Firefox error on save.

- birch-artifact-list-item.html
- Adding preview class to all artifact types for adding event listeners.
- Adding listeners for hover in the ready lifecycle callback. 
- Adding handlers that trigger events that propagate to `gallery-data`, where hovering is handled.
- Changing hide and show functions for thumbnails and story icons so that, if the story has a thumbnail, that is used instead of the story icon.
> Preview changes

- birch-artifact-list-item.css
- birch-artifact-list-item.html
- Contain the icon and the text within the same element
- Update to make sure the .fs-h5 content is white in shadydom
- Move messages over on mobile because select icon overlaps
- Only show icon if the user owns the artifact
> Restricted styles

- birch-artifact-list-item.css
- Positioning the icon and fixing line height for mobile
> Add space and fix line height

- birch-artifact-list-item.html
- Hide the date place data if artifact restricted
- Hide comment count and tag icons if restricted
> Hide date/place if restricted

- locales/birch-artifact-list-item_de.json
- locales/birch-artifact-list-item_en.json
- locales/birch-artifact-list-item_es.json
- locales/birch-artifact-list-item_fr.json
- locales/birch-artifact-list-item_it.json
- locales/birch-artifact-list-item_ja.json
- locales/birch-artifact-list-item_ko.json
- locales/birch-artifact-list-item_pt.json
- locales/birch-artifact-list-item_ru.json
- locales/birch-artifact-list-item_zh.json
> open in new tab

- test/tests.html
> Unit test for opening restricted dialog

- birch-artifact-list-item.css
- bower.json
> Fixing the blue box.

- birch-artifact-list-item.html
Don't show the contributed by if the user isn't logged in
>  Only show contributed by if authenticated

- birch-artifact-list-item.html
- bower.json
- Changed function name
- Listen with data.*
> Listen for data.* to get prop changes

- locales/birch-artifact-list-item-preview_en.json
- locales/birch-artifact-list-item_en.json
- preview is missing the translation string for "Uploading"
- list item needs a new solution for the contributed by translations
- comments icon doesn't have a title attribute
> Update Translation strings

- birch-artifact-list-item-preview.html
> Display upload error message
